trigger:
  - master

pool: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      echo "Generando aws-exports.js..."
      cat <<EOT > src/aws-exports.js
      /* eslint-disable */
      const awsmobile = {
          "aws_project_region": "$(AWS_REGION)",
          "aws_cognito_identity_pool_id": "$(COGNITO_IDENTITY_POOL_ID)",
          "aws_cognito_region": "$(AWS_REGION)",
          "aws_user_pools_id": "$(COGNITO_USER_POOLS_ID)",
          "aws_user_pools_web_client_id": "$(COGNITO_WEB_CLIENT_ID)",
          "oauth": {},
          "aws_cognito_username_attributes": ["EMAIL"],
          "aws_cognito_social_providers": [],
          "aws_cognito_signup_attributes": ["EMAIL", "NICKNAME"],
          "aws_cognito_mfa_configuration": "OFF",
          "aws_cognito_mfa_types": ["SMS"],
          "aws_cognito_password_protection_settings": {
              "passwordPolicyMinLength": 8,
              "passwordPolicyCharacters": []
          },
          "aws_cognito_verification_mechanisms": ["EMAIL"]
      };
      export default awsmobile;
      EOT
    displayName: "Generar aws-exports.js con variables"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - task: AWSCLI@1
    inputs:
      awsCredentials: "aws-connection"
      regionName: "us-east-1"
      awsCommand: "s3"
      awsSubCommand: "sync"
      awsArguments: "./dist s3://nessum-front-v2 --delete"
    displayName: "upload to s3"

  - task: AWSCLI@1
    inputs:
      awsCredentials: "aws-connection"
      awsCommand: "cloudfront"
      awsSubCommand: "create-invalidation"
      awsArguments: '--distribution-id E1XYPSZHNKQZDC --paths "/*"'
    displayName: "invalidate cloudfront"
